### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by kevinsheahan** [fraudlabspro/fraudlabspro-python#1]
It seems that there is a syntax error order.py line 179: 
 else:
    ship_city : ''
The semi-colon (:) should be an equals (=).

**Comment by fraudlabspro-com** [comment]
Hi kevinsheahan, we have fixed the syntax error and push the new version on 833e8eb8cbeec2f72b6a57cea5c4ece8914d47c7. We will close this issue now.
