### ISSUE TITLE
ROUND_UP not imported

### ISSUE THREAD

**Issue by kevinsheahan** [fraudlabspro/fraudlabspro-python#2]
orders.py is throwing an exception (line 80) as ROUND_UP has not been imported. 
Solution:
from decimal import ROUND_UP

**Comment by fraudlabspro-com** [comment]
Hi kevinsheahan, I can't reproduced the exception as what you said. Can you please:

- Provide the Python version that you are using
- A screenshot of the exception

Thank You.

**Comment by kevinsheahan** [comment]
Hi,
Here is the exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kevin/Envs/store357/lib/python3.5/site-packages/libs/order.py", line 81, in validate
    amount = Decimal(amount).quantize(Decimal('.01'), rounding = ROUND_UP)
NameError: name 'ROUND_UP' is not defined

So that would be line 81 of order.py.

I am using Python 3.5.7.

In order to fix this you need the following:
from decimal import ROUND_UP

Thanks and regards,
Kevin Sheahan


--
Kevin Sheahan

Beware of emails purporting to come from Blacknight: https://blacknight.blog/scam-emails-targeting-blacknight.html

http://www.blacknight.host/<https://exchange.blacknight.ie/owa/redir.aspx?C=ui2aWJMYTk-TCLoGujn8ozU4XRNDodEIqTLAbsoEv2eFHw51MX-EQ0Q_HpuI2k3IdvgmFrfILJo.&URL=http%3a%2f%2fwww.blacknight.host%2f>
http://blog.blacknight.com/<https://exchange.blacknight.ie/owa/redir.aspx?C=ui2aWJMYTk-TCLoGujn8ozU4XRNDodEIqTLAbsoEv2eFHw51MX-EQ0Q_HpuI2k3IdvgmFrfILJo.&URL=http%3a%2f%2fblog.blacknight.com%2f>
http://www.technology.ie<https://exchange.blacknight.ie/owa/redir.aspx?C=ui2aWJMYTk-TCLoGujn8ozU4XRNDodEIqTLAbsoEv2eFHw51MX-EQ0Q_HpuI2k3IdvgmFrfILJo.&URL=http%3a%2f%2fwww.technology.ie>
http://www.blacknight.press<https://exchange.blacknight.ie/owa/redir.aspx?C=ui2aWJMYTk-TCLoGujn8ozU4XRNDodEIqTLAbsoEv2eFHw51MX-EQ0Q_HpuI2k3IdvgmFrfILJo.&URL=http%3a%2f%2fwww.blacknight.press> for all our news & media
http://www.blacknight.tech<https://exchange.blacknight.ie/owa/redir.aspx?SURL=Fdy3dUC-HvFtkzT4loDCGGz_GjG3Wa4E04FxOkhOVGTsaSrzxLnSCGgAdAB0AHAAOgAvAC8AdwB3AHcALgBiAGwAYQBjAGsAbgBpAGcAaAB0AC4AdABlAGMAaAA.&URL=http%3a%2f%2fwww.blacknight.tech>  for status

Blacknight Internet Solutions Ltd. <http://blacknight.com/>
12A Barrowside Business Park, Carlow, Ireland
Registered in Ireland, Company No.: 370845

________________________________

**Comment by fraudlabspro-com** [comment]
Hi Sheahan,
Thanks for your information. We are working on fixing it since we finally able to reproduce the issue. Stay tune for the update.

**Comment by fraudlabspro-com** [comment]
Hi @kevinsheahan ,
We have updated the package (https://github.com/fraudlabspro/fraudlabspro-python/commit/41d3686779fcaa39f7bb50aa41481e8fa0476bce) and release a new version of it: https://github.com/fraudlabspro/fraudlabspro-python/releases/tag/1.1.0

Can you please test again and see if the issue still exist?

**Comment by kevinsheahan** [comment]
Could you please make version 1.1.0 available on pypi.org. Also the setup.py refers to README.md but the file name is readme.md and it is case sensitive. Could you please either change setup.py or the name of the file to match. Thanks.

**Comment by kevinsheahan** [comment]
Testing of ver 1.1.0 worked thanks.

**Comment by fraudlabspro-com** [comment]
Hi @kevinsheahan ,

We have released a new version of 1.1.1 on here and PyPI according to your suggestion: https://github.com/fraudlabspro/fraudlabspro-python/releases/tag/1.1.1  

We will close the ticket now as this issue is solved. If you found another issue, please open a new ticket for us to track. Thank You.
